default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :distribute_to_firebase do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
    app: "1:236297363656:android:013f0186330a2022bfc5fd",
    firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],  
    android_artifact_type: "APK",
    android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
    testers: "yousiftareq6@gmail.com",
    release_notes: "First FastLane Firebase Distribution"
  )
  end
end
